### ISSUE TITLE
option to restore from cached db instead of re-downloading

### ISSUE THREAD

**Issue by christophermlne** [PrecisionNutrition/pndev#12]

**Comment by ghedamat** [comment]
I didn't do this because we can't have a cached db for security reasons but I did add a `--quick` option to `pndev prepare`

see `pndev help prepare` for details.
this will NOT download a db and instead use ONLY boostrap data

**Comment by ghedamat** [comment]
https://github.com/PrecisionNutrition/pndev/commit/047173f84706e601aa5edbec9dbd4d0457a12695
