### ISSUE TITLE
pndev start should work in liberator

### ISSUE THREAD

**Issue by typeoneerror** [PrecisionNutrition/pndev#25]
Perhaps add a .pndev config in WORKSPACE/.pndev to tell pndev "how" to start if not defaults

**Comment by ghedamat** [comment]
would love to discuss what you are thinking here.

we could have a `.toml` file that we parse in each repo

`pndev_config.toml`

with something like

```
start_cmd=nix-shell --run bundle ...
```

what would that be for liberator though? given that you don't use `nix-shell` there? (as an aside I think we could totally make nix-shell work there too and avoid having people needing to install `rbenv` and various `node` stuff locally)

**Comment by typeoneerror** [comment]
@ghedamat I think maybe I'd like to take on the work of preparing liberator for pndev (been wanting to do that) and then I could think more about this. I don't think this is really that important right now.

**Comment by typeoneerror** [comment]
Closing for now as this is not possible with Capacitor at this time.
