### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by typeoneerror** [PrecisionNutrition/pndev#5]
Might be nice to add an installer that steps through config and adds to your path. Is "cargo" an option for this?

**Comment by ghedamat** [comment]
@typeoneerror I have a bash one liner ready to go for this that I can share

using cargo is not a good idea because you need the full rust toolchain

ours will work more like

```
curl https://nixos.org/nix/install | sh
```

**Comment by typeoneerror** [comment]
downloading files from gh works fine. happens so infrequently it's not worth the effort.
