### ISSUE TITLE
whitespace and exiting

### ISSUE THREAD

**Issue by typeoneerror** [PrecisionNutrition/pndev#8]
After starting a `pnshell` my prompt is hidden. When you exit, a new line is not sent to the terminal so the text gets mashed up.

Exiting the shell leads to an error:

```
[nix-shell:~/Dev/pn/eternal-sledgehammer](master)$ exit
exit
Error: Shell command failed
```

**Comment by ghedamat** [comment]
can you provide repro steps? I don't see this behaviour :/

**Comment by typeoneerror** [comment]
Not reproducible this morning. Closing for now. Might've been a first-install thing.
